image: Visual Studio 2017
platform: x64
clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive
environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      CPP: 14
      CONFIG: Release
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      CPP: 14
      CONFIG: Release
install:
  - ps: "ls \"C:/\""
  - cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
  - ps: |
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade pip setuptools"
  - "pip install pipenv"

build_script:
  # Build the compiled extension
  - "pipenv install --dev"
  - "pipenv run pip install -e ."

test_script:
  # Run the project tests and store results in .xml log
  - ps: |
      pipenv run python -m unittest discover
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
